server:
  port: 8000

spring:
  application:
    name: gulimall-member
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.181.130:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333

  # 链路追踪 采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

  # 链路追踪可视化
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

logging:
  level:
    com.atguigu.gulimall: debug

# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# sentinel对feign值支持
feign:
  sentinel:
    enabled: true