spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.181.130
    port: 6379
  # spring-session整合
  session:
    store-type: redis
server:
  port: 20000
  # session存活时间
  servlet:
    session:
      timeout: 30m

