server:
  port: 20000

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.181.130:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
  thymeleaf:
    cache: false
  redis:
    host: 192.168.181.130
    port: 6379
  # spring-session整合
  session:
    store-type: redis
  # session存活时间
  servlet:
    session:
      timeout: 30m


# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: *