server:
  port: 15000

spring:
  application:
    name: gulimall-seckill
  cloud:
    # nacos注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # sentinel限流、熔断和降级
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
        port: 8719 #服务和控制台传输数据用的端口
  thymeleaf:
    cache: false
  redis:
    host: 192.168.181.130
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.181.130
    port: 5672
    virtual-host: /

# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# sentinel对feign值支持
feign:
  sentinel:
    enabled: true