spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.181.130:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.181.130
    port: 6379

server:
  port: 15000
