spring:
  application:
    name: gulimall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.181.130:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    # nacos注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # rabbitMQ
  rabbitmq:
    host: 192.168.181.130
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true # 开启发送端确认
    publisher-returns: true  # 开启发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      direct:
        acknowledge-mode: manual # 手动ack确认消息
  session:
    store-type: redis # spring-session
  thymeleaf:
    cache: false
  redis:
    host: 192.168.181.130
    port: 6379
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增

server:
  port: 9000

logging:
  level:
    com.atguigu.gulimall: debug

# 自定义线程池配置
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10