server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.181.130:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
  thymeleaf:
    cache: false
# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: *