server:
  port: 88

spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq # \u53C2\u6570url\u4E3Aqq\uFF0C\u4E5F\u53EF\u4EE5\u5199\u6B63\u5219
#
#        - id: baidu_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu

          - id: gulimall_product_route
            uri: lb://gulimall-product
            predicates:
              - Path=/api/product/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: gulimall_coupon_route
            uri: lb://gulimall-coupon
            predicates:
              - Path=/api/coupon/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: gulimall_thirdparty_route
            uri: lb://gulimall-third-party
            predicates:
              - Path=/api/thirdparty/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: gulimall_member_route
            uri: lb://gulimall-member
            predicates:
              - Path=/api/member/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: gulimall_ware_route
            uri: lb://gulimall-ware
            predicates:
              - Path=/api/ware/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: gulimall_admin_route
            uri: lb://renren-fast
            predicates:
              - Path=/api/**
            filters:
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

          - id: gulimall_host_route
            uri: lb://gulimall-product
            predicates:
              - Host=gulimall.com,item.gulimall.com

          - id: gulimall_search_route
            uri: lb://gulimall-search
            predicates:
              - Host=search.gulimall.com

          - id: gulimall_auth_route
            uri: lb://gulimall-auth-server
            predicates:
              - Host=auth.gulimall.com

          - id: gulimall_cart_route
            uri: lb://gulimall-cart
            predicates:
              - Host=cart.gulimall.com

          - id: gulimall_order_route
            uri: lb://gulimall-order
            predicates:
              - Host=order.gulimall.com

          - id: gulimall_seckill_host
            uri: lb://gulimall-seckill
            predicates:
              - Host=seckill.gulimall.com
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333

# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: *