server:
  port: 30000

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: xxx # 使用nacos配置(会覆盖当前配置)
      secret-key: xxx # 使用nacos配置(会覆盖当前配置)
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-ferris
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appCode: e8fe660ecc7a4982a9ab6be0be4b6127
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333

  # 链路追踪 采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

  # 链路追踪可视化
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: false

# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# sentinel对feign值支持
feign:
  sentinel:
    enabled: true