server:
  port: 40000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333

  # 链路追踪 采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

  # 链路追踪可视化
  zipkin:
    base-url: http://192.168.181.130:9411
    sender:
      type: web
    discovery-client-enabled: false

  redis:
    host: 192.168.181.130

# 自定义线程池配置
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
# actuator暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# sentinel对feign值支持
feign:
  sentinel:
    enabled: true