spring:
  application:
    name:gulimall-ware
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.181.130:3306/gulimall_wms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # \u4E3B\u952E\u81EA\u589E
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #\u5F00\u542Fsql\u65E5\u5FD7

server:
  port: 11000